// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mclfsonvglxogbxmlazx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbGZzb252Z2x4b2dieG1sYXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTk0MjEsImV4cCI6MjA3MjkzNTQyMX0.5aKmVA3wE1F1ZiPk3mjYwxEMiwzGzCtPQXsgWFK4KzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});